// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDxl3ra0mKfpX3PNvfKk6dhrdZtmIguk',
    appId: '1:493874779503:web:cde447b1668c224bbe049a',
    messagingSenderId: '493874779503',
    projectId: 'disaster-app-bae22',
    authDomain: 'disaster-app-bae22.firebaseapp.com',
    storageBucket: 'disaster-app-bae22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvT11TVinCxdQhTuP_zSYLN4YnmScwPZ8',
    appId: '1:493874779503:android:7c2068c73e5459d7be049a',
    messagingSenderId: '493874779503',
    projectId: 'disaster-app-bae22',
    storageBucket: 'disaster-app-bae22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY3BF3SPOpvWXWGRI5bcwx3489mRYCahY',
    appId: '1:493874779503:ios:e4d2299228f17758be049a',
    messagingSenderId: '493874779503',
    projectId: 'disaster-app-bae22',
    storageBucket: 'disaster-app-bae22.appspot.com',
    iosBundleId: 'com.fiveDevHacks.merchantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY3BF3SPOpvWXWGRI5bcwx3489mRYCahY',
    appId: '1:493874779503:ios:39c81696e6d94e74be049a',
    messagingSenderId: '493874779503',
    projectId: 'disaster-app-bae22',
    storageBucket: 'disaster-app-bae22.appspot.com',
    iosBundleId: 'com.example.merchantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDxl3ra0mKfpX3PNvfKk6dhrdZtmIguk',
    appId: '1:493874779503:web:bbcd96007ed119adbe049a',
    messagingSenderId: '493874779503',
    projectId: 'disaster-app-bae22',
    authDomain: 'disaster-app-bae22.firebaseapp.com',
    storageBucket: 'disaster-app-bae22.appspot.com',
  );
}
